### ISSUE TITLE
Error on loading in macos monterey using node v18, But when I running in windows it's normal, How to resolve?

### ISSUE THREAD

**Issue by handita** [bailihuiyue/ant-design-pro-vue3#11]
Hello, sory for inconvenience, I got error when running it in macos montery using same setup it works in windows I got this error

```
TypeError: Cannot destructure property 'prefixCls' of 'useInjectMenu(...)' as it is undefined.
    at InternalSubMenuList (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/ant-design-vue.js?v=c971e4f3:32693:5)
    at renderComponentRoot (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:2352:31)
    at ReactiveEffect.componentUpdateFn [as fn] (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7457:46)
    at ReactiveEffect.run (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:430:19)
    at instance.update (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7588:17)
    at setupRenderEffect (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7598:5)
    at mountComponent (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7366:7)
    at processComponent (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7320:9)
    at patch (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:6786:11)
    at ReactiveEffect.componentUpdateFn [as fn] (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7464:11)
```
    
    
    And this error
    
    
System Error
```
TypeError: dayjs(...).weekday is not a function
    at getDateTime (http://localhost:5173/components/LockScreen/index.vue:41:28)
    at setup (http://localhost:5173/components/LockScreen/index.vue:47:26)
    at callWithErrorHandling (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:1652:19)
    at setupStatefulComponent (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:9063:25)
    at setupComponent (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:9024:36)
    at mountComponent (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7354:7)
    at processComponent (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7320:9)
    at patch (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:6786:11)
    at mountChildren (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7034:7)
    at processFragment (http://localhost:5173/@fs/Volumes/HDD/Projects/envidi-new/node_modules/.vite/deps/chunk-ENB22RO2.js?v=c971e4f3:7250:7)
```

Thank for your help
![image](https://github.com/bailihuiyue/ant-design-pro-vue3/assets/2508835/2156b82d-773b-4e52-8984-0ada6570a66c)

**Comment by bailihuiyue** [comment]
hello friend, is this issue happened in windows? i don`t have macos device

**Comment by handita** [comment]
Nope, It works in windows.. I develop electron app that require macos build.. 

But strangely it don't work in macos

**Comment by handita** [comment]
It solved, just fix dayjs and now its working
