### ISSUE TITLE
访问报错

### ISSUE THREAD

**Issue by felix1982** [bailihuiyue/ant-design-pro-vue3#3]
15:46:38 [vite] Internal server error: Failed to resolve import "./chunk-U3TMEWQO.js" from "node_modules\.vite\chunk-ZOJNSJDI.js?v=43d1ee35". Does the file exist?
  Plugin: vite:import-analysis
  File: F:/src/GitLab/Hotel-Test-Toolkit/list/list-web/node_modules/.vite/chunk-ZOJNSJDI.js?v=43d1ee35
  2  |    __esm,
  3  |    __export
  4  |  } from "./chunk-U3TMEWQO.js";
     |          ^
  5  |  
  6  |  // node_modules/@vue/shared/dist/shared.esm-bundler.js
      at formatError (F:\src\GitLab\Hotel-Test-Toolkit\list\list-web\node_modules\vite\dist\node\chunks\dep-76613303.js:36769:46)
      at TransformContext.error (F:\src\GitLab\Hotel-Test-Toolkit\list\list-web\node_modules\vite\dist\node\chunks\dep-76613303.js:36765:19)
      at normalizeUrl (F:\src\GitLab\Hotel-Test-Toolkit\list\list-web\node_modules\vite\dist\node\chunks\dep-76613303.js:73686:26)
      at async TransformContext.transform (F:\src\GitLab\Hotel-Test-Toolkit\list\list-web\node_modules\vite\dist\node\chunks\dep-76613303.js:73826:57)
      at async Object.transform (F:\src\GitLab\Hotel-Test-Toolkit\list\list-web\node_modules\vite\dist\node\chunks\dep-76613303.js:36985:30)
      at async doTransform (F:\src\GitLab\Hotel-Test-Toolkit\list\list-web\node_modules\vite\dist\node\chunks\dep-76613303.js:52049:29)
15:46:38 [vite] Failed to load source map for /node_modules/.vite/crypto-js_aes.js?v=b9d020d1.

**Comment by bailihuiyue** [comment]
下午3:50:08 [vite] Failed to load source map for /node_modules/.vite/chunk-QL4ZTGIQ.js?v=7f68fdde.
下午3:50:08 [vite] Failed to load source map for /node_modules/.vite/@ant-design_icons-vue.js?v=7f68fdde.
下午3:50:08 [vite] Failed to load source map for /node_modules/.vite/moment.js?v=7f68fdde.
下午3:53:04 [vite] ✨ dependencies updated, reloading page...
下午3:53:07 [vite] new dependencies found: ant-design-vue/es/badge/style/css, updating...
下午3:53:07 [vite] Failed to load source map for /node_modules/.vite/axios.js?v=35336e00.
@aesoper/normal-utils doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

类似的报错是正常的,项目第一次启动会有缓存,等几分钟好了以后就不会报错了
