### ISSUE TITLE
按照说明文档 安装还是错误的

### ISSUE THREAD

**Issue by Jzow** [bailihuiyue/ant-design-pro-vue3#9]
```
VITE v4.4.9  ready in 1373 ms

  ➜  Local:   http://127.0.0.1:5174/
  ➜  Network: use --host to expose
  ➜  press h to show help

  Apite server running at:
  > Doc:      http://localhost:5174/api/
X [ERROR] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package [plugin vite:dep-pre-bundle]

    node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///E:/opensource/ant-design-pro-vue3/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
    at resolvePackageEntry (file:///E:/opensource/ant-design-pro-vue3/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
    at tryNodeResolve (file:///E:/opensource/ant-design-pro-vue3/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Context.resolveId (file:///E:/opensource/ant-design-pro-vue3/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.resolveId (file:///E:/opensource/ant-design-pro-vue3/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///E:/opensource/ant-design-pro-vue3/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
    at async file:///E:/opensource/ant-design-pro-vue3/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34
    at async requestCallbacks.on-resolve (E:\opensource\ant-design-pro-vue3\node_modules\esbuild\lib\main.js:1373:22)
    at async handleRequest (E:\opensource\ant-design-pro-vue3\node_modules\esbuild\lib\main.js:729:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///E:/opensource/ant-design-pro-vue3/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)
    at handlePlugins (E:\opensource\ant-design-pro-vue3\node_modules\esbuild\lib\main.js:1292:21)
    at buildOrContextImpl (E:\opensource\ant-design-pro-vue3\node_modules\esbuild\lib\main.js:978:5)
    at Object.buildOrContext (E:\opensource\ant-design-pro-vue3\node_modules\esbuild\lib\main.js:786:5)
    at E:\opensource\ant-design-pro-vue3\node_modules\esbuild\lib\main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (E:\opensource\ant-design-pro-vue3\node_modules\esbuild\lib\main.js:2186:27)
    at Object.context (E:\opensource\ant-design-pro-vue3\node_modules\esbuild\lib\main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///E:/opensource/ant-design-pro-vue3/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
      8 │ var shared = require('@intlify/shared');
```

**Comment by Jzow** [comment]
`yarn add @intlify/shared `添加了也不行 靠谱不靠谱啊

**Comment by bailihuiyue** [comment]
> `yarn add @intlify/shared `添加了也不行 靠谱不靠谱啊

解决了吗,老铁

**Comment by Jzow** [comment]
@bailihuiyue 好像是版本ant design有问题，我用的4.0，3.0应该没啥问题，它有时候报告错误说theme没有
